ServerName localhost

ProxyPreserveHost On

ProxyPass /api/ http://backend-api:8080/
ProxyPassReverse /api/ http://backend-api:8080/

ProxyPass /departments http://backend-api:8080/departments
ProxyPassReverse /departments http://backend-api:8080/departments

ProxyPass /students http://backend-api:8080/students
ProxyPassReverse /students http://backend-api:8080/students
